Traceback (most recent call last):
  File "/Users/naresh/miniconda3/envs/books/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/naresh/miniconda3/envs/books/lib/python3.9/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/naresh/miniconda3/envs/books/lib/python3.9/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/Users/naresh/miniconda3/envs/books/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/naresh/miniconda3/envs/books/lib/python3.9/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Users/naresh/miniconda3/envs/books/lib/python3.9/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/naresh/miniconda3/envs/books/lib/python3.9/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from testing_manim import *

log_capture_string, ch, logger = start()

class Naresh(Scene):
    def construct(self):
        circle = Circle(radius=1, color=BLUE)
        dot = Dot()
        text = Text("Naresh2")
        self.play(Write(text))
        dot2 = dot.copy().shift(RIGHT)
        self.add(dot)
        line = Line([3, 0, 0], [5, 0, 0])
        self.add(line)
        self.play(GrowFromCenter(circle))
        self.play(Transform(dot, dot2))
        self.play(MoveAlongPath(dot, circle), run_time=2, rate_func=linear)
        self.play(Rotating(dot, about_point=[2, 0, 0]), run_time=1.5)
        self.wait()

quality_flag = "-qm" # Example: "-ql", "-qm", "-qh", "-qk"
sc = Naresh()

set_res(quality_flag)
show(quality_flag, sc)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[1], line 1[0m
[0;32m----> 1[0m [38;5;28;01mfrom[39;00m [38;5;21;01mtesting_manim[39;00m [38;5;28;01mimport[39;00m [38;5;241m*[39m
[1;32m      3[0m log_capture_string, ch, logger [38;5;241m=[39m start()
[1;32m      5[0m [38;5;28;01mclass[39;00m [38;5;21;01mNaresh[39;00m(Scene):

File [0;32m~/Downloads/dsa-book.github.io/docs/testing_manim.py:1[0m
[0;32m----> 1[0m [38;5;28;01mfrom[39;00m [38;5;21;01mmanim[39;00m [38;5;28;01mimport[39;00m [38;5;241m*[39m
[1;32m      2[0m [38;5;28;01mimport[39;00m [38;5;21;01mrequests[39;00m
[1;32m      3[0m [38;5;28;01mfrom[39;00m [38;5;21;01mIPython[39;00m[38;5;21;01m.[39;00m[38;5;21;01mdisplay[39;00m [38;5;28;01mimport[39;00m HTML, display, clear_output

[0;31mModuleNotFoundError[0m: No module named 'manim'

